Simple frontend
kabachook/domain-checker pull request #4
Opened 2018-10-25 16:03 UTC by kabachook

Self-explanatory

2018-10-25 16:41 UTC, gohabereg requested changes

2018-10-25 16:41 UTC, gohabereg commented on frontend/src/js/main.js
> +  const response = await fetch('http://localhost:3000' + DOMAIN_ENDPOINT + domain);
Надо разхардкодить урл

2018-10-25 16:41 UTC, gohabereg commented on frontend/src/js/main.js
> +  console.log(resp);
Лог убрать

2018-10-25 16:41 UTC, gohabereg commented on frontend/src/js/main.js
> +  const resultElement = document.querySelector(RESULT_DIV);
Если у тебя у этих элементов есть id, то лучше искать по id

2018-10-25 16:41 UTC, gohabereg commented on frontend/src/js/main.js
> +    if (Object.keys(data).indexOf('available') !== -1 && data['available'] === true) {
Можно просто вот так. Если такого ключа нет, то `data.available === undefined`
```suggestion
    if (data.available === true) {
```

2018-10-25 16:41 UTC, gohabereg commented on frontend/src/js/main.js
> +onload = _ => {
```suggestion
onload = () => {
```

2018-10-25 16:41 UTC, gohabereg commented on frontend/src/js/main.js
> +      // resultElement.appendChild(document.createElement('break'));
Лишние строки убирай

2018-10-25 16:41 UTC, gohabereg commented on frontend/src/js/main.js
> +    if (event.keyCode === 13 || event.keyCode === 10) {
Коды клавиш надо расхардкодить

2018-10-25 16:41 UTC, gohabereg commented on frontend/src/js/main.js
> +const SEARCH_THRESHHOLD = 1000;
Все методы в этом файле надо или оформить в класс, или обернуть в замыкание

2018-11-06 16:39 UTC, neSpecc requested changes

2018-11-06 16:39 UTC, neSpecc commented on frontend/src/css/main.css
> +    font-family: 'Inconsolata', monospace;
надо использовать системные шрифты

2018-11-06 16:39 UTC, neSpecc commented on frontend/src/js/main.js
> +  const API_URI = 'http://localhost:3000';
надо задокументировать код, описать все методы, константы, параметры и тд

2018-11-06 16:39 UTC, neSpecc commented on frontend/src/js/main.js
> +  const searchDomain = async (domain) => {
async нельзя использовать без специальных полифиллов

2018-11-06 16:39 UTC, neSpecc commented on frontend/src/index.html
> +<h1>Hello, World!</h1>
нет табуляции

2018-11-06 16:39 UTC, neSpecc requested changes

2018-11-06 16:39 UTC, neSpecc commented on frontend/package.json
> +    "name": "frontend",
тут указывается название проекта

2019-02-02 19:49 UTC, kabachook commented
Moved to github.com/codex-team/domain-checker

2019-02-02 19:49 UTC, closed without merging